#!/usr/bin/env bash
# Install SGLang-Omni and download Higgs Audio v3 weights on a Linux GPU machine.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

MODEL_ID="${MODEL_ID:-bosonai/higgs-audio-v3-tts-4b}"
SGLANG_OMNI_DIR="${SGLANG_OMNI_DIR:-$(dirname "$REPO_ROOT")/sglang-omni}"
MODEL_LOCAL_DIR="${MODEL_LOCAL_DIR:-$REPO_ROOT/models/$MODEL_ID}"

echo "==> Higgs Audio v3 GPU setup"
echo "    Repo root:      $REPO_ROOT"
echo "    Model:          $MODEL_ID"
echo "    Model dir:      $MODEL_LOCAL_DIR"
echo "    SGLang-Omni:    $SGLANG_OMNI_DIR"

if ! command -v nvidia-smi >/dev/null 2>&1; then
  echo "WARNING: nvidia-smi not found. Continue only if you are on a machine with NVIDIA drivers (or inside the sglang-omni Docker image)."
else
  nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader
fi

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: required command not found: $1"
    exit 1
  fi
}

need_cmd git
need_cmd curl

if ! command -v hf >/dev/null 2>&1; then
  echo "==> Installing Hugging Face CLI..."
  curl -LsSf https://hf.co/cli/install.sh | bash
  export PATH="${HOME}/.local/bin:${PATH}"
fi
need_cmd hf

if ! hf auth whoami >/dev/null 2>&1; then
  echo "==> Log in to Hugging Face (needed for model download):"
  hf auth login
fi

if [[ ! -d "$SGLANG_OMNI_DIR/.git" ]]; then
  echo "==> Cloning SGLang-Omni..."
  git clone https://github.com/sgl-project/sglang-omni.git "$SGLANG_OMNI_DIR"
else
  echo "==> SGLang-Omni already cloned at $SGLANG_OMNI_DIR"
fi

if ! command -v uv >/dev/null 2>&1; then
  echo "==> Installing uv..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="${HOME}/.local/bin:${PATH}"
fi
need_cmd uv

echo "==> Installing SGLang-Omni (editable)..."
cd "$SGLANG_OMNI_DIR"
uv venv .venv -p 3.12
# shellcheck disable=SC1091
source .venv/bin/activate
uv pip install -v -e .

echo "==> Downloading model weights (this may take a while)..."
mkdir -p "$(dirname "$MODEL_LOCAL_DIR")"
hf download "$MODEL_ID" --local-dir "$MODEL_LOCAL_DIR"

mkdir -p "$SCRIPT_DIR/output"

cat >"$SCRIPT_DIR/.env" <<EOF
# Generated by setup_gpu.sh — edit as needed
MODEL_ID=$MODEL_ID
MODEL_LOCAL_DIR=$MODEL_LOCAL_DIR
SGLANG_OMNI_DIR=$SGLANG_OMNI_DIR
SERVE_PORT=${SERVE_PORT:-8000}
SERVE_HOST=${SERVE_HOST:-0.0.0.0}
EOF

echo ""
echo "Setup complete."
echo ""
echo "Next steps:"
echo "  1. Start server:  $SCRIPT_DIR/serve.sh"
echo "  2. Run tests:     python $SCRIPT_DIR/test_client.py --quick"
echo "  3. Multilingual:  python $SCRIPT_DIR/test_multilingual.py"
echo ""
echo "If install fails on bare metal, use Docker — see SETUP_V3_GPU.md"
